### PR TITLE
chore: Update theme.liquid and pr-preview.yml files

### PR DESCRIPTION
**Pull request by KedarMalapDev**

### CODE REVIEW

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!unlock-preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!unlock-preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Pull request closed without merging**
