### PR TITLE
Update about-us.liquid

### PR DESCRIPTION
**Pull request by KedarMalapDev**

### CODE REVIEW

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!unlock-preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Comment by dd-anish** [comment]
!preview

**Pull request closed without merging**
